// Generated by CoffeeScript 1.7.1
(function() {
  var getcoindeskdata, http;

  http = require('http');

  getcoindeskdata = function(foo_dosomething) {
    return http.get('http://api.coindesk.com/v1/bpi/currentprice.json', function(res) {
      res.setEncoding('utf8');
      return res.on('data', function(data) {
        return foo_dosomething(eval('(' + data + ')'));
      });
    });
  };

  module.exports = getcoindeskdata;

}).call(this);
